je-me-presente/config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/', to: 'static_pages#home'
  get 'contact', to: 'static_pages#contact'
  get 'about', to: 'static_pages#about'
  get '/about/le-goupe', to: 'static_pages#le_groupe', as: 'groupe'
  get '/about/moi', to: 'static_pages#moi', as: 'yo'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

je-me-presente/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

je-me-presente/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

je-me-presente/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def contact
  end

  def about
  end

  def yo
  end

  def groupe
  end
end

je-me-presente/app/helpers/application_helper.rb
module ApplicationHelper
end

je-me-presente/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

je-me-presente/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Jemepresente</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css"/>

  </head>

  <body>
    <%= yield %>
  </body>
</html>

je-me-presente/app/views/static_pages/about.html.erb
<h1>About</h1>
<p>Projet du groupe</p>
<h3>Qui sommes nous ?</h3>
<ul>
    <li><%= link_to 'Notre Groupe', groupe_path %></li>
    <li><%= link_to 'Moi', yo_path %></li>
</ul>

<p><%= link_to '<- Homepage', root_path %></p>

je-me-presente/app/views/static_pages/contact.html.erb
<h1>StaticPages#contact</h1>
<p>Find me in app/views/static_pages/contact.html.erb</p>

je-me-presente/app/views/static_pages/home.html.erb
<h1>Home</h1>
<p>Bienvenu sur notre site!</p>

<p><%= link_to 'À propos de nous', about_path %></p>

je-me-presente/app/views/static_pages/le_groupe.html.erb
<h1>C'est NOUS!</h1>
</br>
</br>

je-me-presente/app/views/static_pages/moi.html.erb
<h1>C'est moi</h1>
</br>
</br>